# Generated by Django 2.2.1 on 2019-05-14 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20190508_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='expire',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
